title: Qgoda
linguas: [en, de]
exclude: [node_modules, package.json, gulpfile.js]
helpers:
  - gulp
defaults:
  posts:
    values:
      type: post
    subdirs:
      en:
        values:
          linguas: en
      de:
        values:
          linguas: de
taxonomies:
  'doc-section': ~
