title: Qgoda
linguas: [en, de]
exclude: 
  - /node_modules
  - /package.json
  - /gulpfile.js
  - /package-lock.json
helpers:
  gulp: npm start
  browser-sync: npm run server
defaults:
  - files: /posts
    values:
      type: post
  - files: /posts/en
    values:
      lingua: en
  - files: /posts/de
    values:
      lingua: de
  - files: /en
    values:
      lingua: en
  - files: /de
    values:
      lingua:
        de
taxonomies:
  'doc-section': ~
  name: ~
processors:
  chains:
    html:
      modules:
        - TT2
        - HTMLCleaner
po:
  xgettext:
    text:
      - en

# This should be overridden in _localconfig.yaml or in a private branch.
legal:
  name: configure legal.name in _localconfig.yamg or _config.yaml
  street: configure legal.name in _localconfig.yamg or _config.yaml
  city: configure legal.name in _localconfig.yamg or _config.yaml
  id: configure legal.name in _localconfig.yamg or _config.yaml
  vat-id: configure legal.name in _localconfig.yamg or _config.yaml
  copyright_year: configure legal.name in _localconfig.yamg or _config.yaml
  copyright_uri: configure legal.name in _localconfig.yamg or _config.yaml
google:
  #analytics_id: 'UA-XXXXXXX-X'
