title: Qgoda
linguas: [en, de]
exclude: 
  - /node_modules
  - /package.json
  - /webpack.config.js
  - /yarn.lock
  - /TODO
  - /postcss.config.js
exclude_watch:
  - /assets
  - "!/_timestamp.json"
helpers:
  yarn: yarn start
  browser-sync: yarn server
defaults:
  - files:
      - /*/**
      - '!/en/'
    values:
      translate: [title, description] 
  - files: /posts
    values:
      type: post
  - files: /posts/en
    values:
      lingua: en
  - files: /posts/de
    values:
      lingua: de
  - files: /en
    values:
      lingua: en
  - files: /de
    values:
      lingua:
        de
taxonomies:
  'doc-section': ~
  name: ~
processors:
  chains:
    html:
      modules:
        - TT2
        - HTMLCleaner
    markdown:
      modules:
      - TT2
      - Hoedown
po:
  textdomain: 'net.qgoda.www'

# This should be overridden in _localconfig.yaml or in a private branch.
legal:
  name: configure legal.name in _localconfig.yamg or _config.yaml
  street: configure legal.name in _localconfig.yamg or _config.yaml
  city: configure legal.name in _localconfig.yamg or _config.yaml
  id: configure legal.name in _localconfig.yamg or _config.yaml
  vat-id: configure legal.name in _localconfig.yamg or _config.yaml
  copyright_year: configure legal.name in _localconfig.yamg or _config.yaml
  copyright_uri: configure legal.name in _localconfig.yamg or _config.yaml
google:
  #analytics_id: 'UA-XXXXXXX-X'
