title: Qgoda
linguas: [en, de]
exclude: 
  - /node_modules
  - /package.json
  - /webpack.config.js
  - /yarn.lock
  - /TODO
  - /LocaleData
  - /postcss.config.js
exclude_watch:
  - /assets
  - "!/_timestamp.json"
helpers:
  yarn: yarn start
  browser-sync: yarn server
defaults:
  - files:
      - /*/**
      - '!/en/'
    values:
      translate: [title, description, image_alt] 
  - files: /en
    values:
      lingua: en
  - files: /de
    values:
      lingua: de
  - files: /*/docs/**
    values:
      type: doc 
      navsection: docs
  - files: /*/news/**
    values:
      type: post
      navsection: news
  - files: [index.md, index.html]
    values:
      type: page
      priority: 999
taxonomies:
  'doc-section': ~
  name: ~
processors:
  chains:
    markdown:
      modules:
      - TT2
      - Hoedown
po:
  textdomain: net.qgoda.www
  msgid_bugs_address: Guido Flohr <guido.flohr@cantanea.com>
  copyright_holder: cantanea EOOD <http://www.cantanea.com/>
  qgoda:
    - perl 
    - -I/Users/guido/perl/qgoda/lib 
    - /Users/guido/perl/qgoda/qgoda

# This should be overridden in _localconfig.yaml or in a private branch.
legal:
  name: configure legal.name in _localconfig.yamg or _config.yaml
  street: configure legal.name in _localconfig.yamg or _config.yaml
  city: configure legal.name in _localconfig.yamg or _config.yaml
  id: configure legal.name in _localconfig.yamg or _config.yaml
  vat-id: configure legal.name in _localconfig.yamg or _config.yaml
  copyright_year: configure legal.name in _localconfig.yamg or _config.yaml
  copyright_uri: configure legal.name in _localconfig.yamg or _config.yaml
google:
  #analytics_id: 'UA-XXXXXXX-X'
