title: Qgoda
linguas: [en, de]
exclude: [node_modules, package.json, gulpfile.js]
helpers:
  gulp: npm start
  browser-sync: npm run server
defaults:
  - files: /posts
    values:
      type: post
  - files: /posts/en
    values:
      lingua: en
  - files: /posts/de
    values:
      lingua: de
  - files: /en
    values:
      lingua: en
  - files: /de
    values:
      lingua:
        de
taxonomies:
  'doc-section': ~
  name: ~
processors:
  chains:
    html:
      modules:
        - TT2
        - HTMLCleaner
po:
  xgettext:
    text:
      - en
