title: Qgoda
linguas: [en, de]
exclude: [node_modules, package.json, gulpfile.js]
helpers:
  - gulp
defaults:
  posts:
    values:
      type: post
    subdirs:
      en:
        values:
          lingua: en
      de:
        values:
          lingua: de
  en:
    values:
      lingua: en
  de:
    values:
      lingua: de
taxonomies:
  'doc-section': ~
